<a href="https://colab.research.google.com/github/7201krap/PYTORCH_project/blob/main/same_label_pair.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch.utils.data import DataLoader, Subset
import torchvision.datasets as datasets
from torchvision import transforms
import numpy as np

In [2]:
mnist_trainset = datasets.MNIST(root='./data', train=True, 
                                download=True, 
                                transform=transforms.Compose([transforms.ToTensor()]))

mnist_testset  = datasets.MNIST(root='./data', 
                                train=False, 
                                download=True, 
                                transform=transforms.Compose([transforms.ToTensor()]))

In [3]:
# 0 에 해당하는 index 
print(torch.where(mnist_trainset.targets == 0))
# 1 에 해당하는 index 
print(torch.where(mnist_trainset.targets == 1))
# 2 에 해당하는 index 
print(torch.where(mnist_trainset.targets == 2))
# 3 에 해당하는 index 
print(torch.where(mnist_trainset.targets == 3))
# 4 에 해당하는 index 
print(torch.where(mnist_trainset.targets == 4))
# 5 에 해당하는 index 
print(torch.where(mnist_trainset.targets == 5))
# 6 에 해당하는 index 
print(torch.where(mnist_trainset.targets == 6))
# 7 에 해당하는 index 
print(torch.where(mnist_trainset.targets == 7))
# 8 에 해당하는 index 
print(torch.where(mnist_trainset.targets == 8))
# 9 에 해당하는 index 
print(torch.where(mnist_trainset.targets == 9))

(tensor([    1,    21,    34,  ..., 59952, 59972, 59987]),)
(tensor([    3,     6,     8,  ..., 59979, 59984, 59994]),)
(tensor([    5,    16,    25,  ..., 59983, 59985, 59991]),)
(tensor([    7,    10,    12,  ..., 59978, 59980, 59996]),)
(tensor([    2,     9,    20,  ..., 59943, 59951, 59975]),)
(tensor([    0,    11,    35,  ..., 59968, 59993, 59997]),)
(tensor([   13,    18,    32,  ..., 59982, 59986, 59998]),)
(tensor([   15,    29,    38,  ..., 59963, 59977, 59988]),)
(tensor([   17,    31,    41,  ..., 59989, 59995, 59999]),)
(tensor([    4,    19,    22,  ..., 59973, 59990, 59992]),)


In [4]:
torch.where(mnist_trainset.targets == 1)[0]

tensor([    3,     6,     8,  ..., 59979, 59984, 59994])

In [5]:
# class_inds 이거는 그냥 위에있는거를 list 로 만들어준 형태임 
class_inds = [torch.where(mnist_trainset.targets == class_idx)[0]
              for class_idx in mnist_trainset.class_to_idx.values()]

In [6]:
class_inds

[tensor([    1,    21,    34,  ..., 59952, 59972, 59987]),
 tensor([    3,     6,     8,  ..., 59979, 59984, 59994]),
 tensor([    5,    16,    25,  ..., 59983, 59985, 59991]),
 tensor([    7,    10,    12,  ..., 59978, 59980, 59996]),
 tensor([    2,     9,    20,  ..., 59943, 59951, 59975]),
 tensor([    0,    11,    35,  ..., 59968, 59993, 59997]),
 tensor([   13,    18,    32,  ..., 59982, 59986, 59998]),
 tensor([   15,    29,    38,  ..., 59963, 59977, 59988]),
 tensor([   17,    31,    41,  ..., 59989, 59995, 59999]),
 tensor([    4,    19,    22,  ..., 59973, 59990, 59992])]

In [7]:
# class_inds[x] 에는 숫자 x 에 해당하는 mnist 데이터의 index 를 반환 (x = 0, 1, 2 .... 9)

# class_inds[0] 에는 숫자 0 에 해당하는 mnist 데이터의 index 를 반환
print(class_inds[0])
print(class_inds[1])
print(class_inds[2])
print(class_inds[3])
print(class_inds[4])
print(class_inds[5])
print(class_inds[6])
print(class_inds[7])
print(class_inds[8])
print(class_inds[9])

tensor([    1,    21,    34,  ..., 59952, 59972, 59987])
tensor([    3,     6,     8,  ..., 59979, 59984, 59994])
tensor([    5,    16,    25,  ..., 59983, 59985, 59991])
tensor([    7,    10,    12,  ..., 59978, 59980, 59996])
tensor([    2,     9,    20,  ..., 59943, 59951, 59975])
tensor([    0,    11,    35,  ..., 59968, 59993, 59997])
tensor([   13,    18,    32,  ..., 59982, 59986, 59998])
tensor([   15,    29,    38,  ..., 59963, 59977, 59988])
tensor([   17,    31,    41,  ..., 59989, 59995, 59999])
tensor([    4,    19,    22,  ..., 59973, 59990, 59992])


In [8]:
train_dataloaders = [
                     DataLoader(dataset=Subset(mnist_trainset, inds),
                                batch_size=25,
                                shuffle=True,
                                drop_last=False
                     )
                     for inds in class_inds
]

test_dataloader  = torch.utils.data.DataLoader(mnist_testset, 
                                               batch_size=50, 
                                               shuffle=False)

print("Training dataset size: ", len(mnist_trainset))
print("Testing dataset size: ",  len(mnist_testset))

Training dataset size:  60000
Testing dataset size:  10000


In [9]:
# train_dataloaders 는 전체 10 개의 세트를 가지고 있다. 
# 여기서 10개란: 0, 1, 2, ... 9 
train_dataloaders

In [10]:
# Define the model 
class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear_1 = torch.nn.Linear(784, 256)
        self.linear_2 = torch.nn.Linear(256, 10)
        self.sigmoid  = torch.nn.Sigmoid()

    def forward(self, x):
        x = x.reshape(x.size(0), -1)
        x = self.linear_1(x)
        x = self.sigmoid(x)
        pred = self.linear_2(x)

        return pred

In [11]:
model = Model()

In [12]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [13]:
epochs = 30

In [14]:
criterion = torch.nn.CrossEntropyLoss()

test_acc   = list()

for epoch in range(epochs):

    print(f"epoch {epoch} started")

    model.train()
    itr = 0 
    iterators = list(map(iter, train_dataloaders))   
    while iterators:    # this is same as for loop for training 
        itr = itr + 1 
        iterator = np.random.choice(iterators, 2, replace=False)
        
        try:
            image0, label0 = next(iterator[0]) 
            image1, label1 = next(iterator[1]) 

            # concat batch_size 25 * 2 => 50
            image = torch.cat((image0, image1), 0)
            label = torch.cat((label0, label1), 0)

            # print(label.shape)
            # print(image.shape)

            # print(label)

            optimizer.zero_grad()

            pred = model(image)

            loss = criterion(pred, label)

            loss.backward()
            optimizer.step()
            
        except StopIteration:
            iterators.remove(iterator[0])
            iterators.remove(iterator[1])

    model.eval()
    total = 0
    for itr, (image, label) in enumerate(test_dataloader):

        pred = model(image)

        loss = criterion(pred, label)

        # we now need softmax because we are testing.
        pred = torch.nn.functional.softmax(pred, dim=1)
        for i, p in enumerate(pred):
            if label[i] == torch.max(p.data, 0)[1]:
                total = total + 1

    accuracy = total / len(mnist_testset)

    print(accuracy)

    # append accuracy here
    test_acc.append(accuracy)

epoch 0 started
0.7014
epoch 1 started
0.7885
epoch 2 started
0.8281
epoch 3 started
0.8949
epoch 4 started
0.834
epoch 5 started
0.8764
epoch 6 started
0.8749
epoch 7 started
0.8981
epoch 8 started
0.8914
epoch 9 started
0.9224
epoch 10 started
0.9354
epoch 11 started
0.9428
epoch 12 started
0.9326
epoch 13 started
0.9429
epoch 14 started
0.9382
epoch 15 started
0.9356
epoch 16 started
0.9105
epoch 17 started
0.9509
epoch 18 started
0.9622
epoch 19 started
0.9526
epoch 20 started
0.946
epoch 21 started
0.9465
epoch 22 started
0.9653
epoch 23 started
0.9663
epoch 24 started
0.9598
epoch 25 started
0.9519
epoch 26 started
0.9613
epoch 27 started
0.9581
epoch 28 started
0.9691
epoch 29 started
0.9692


In [15]:
test_acc

[0.7014,
 0.7885,
 0.8281,
 0.8949,
 0.834,
 0.8764,
 0.8749,
 0.8981,
 0.8914,
 0.9224,
 0.9354,
 0.9428,
 0.9326,
 0.9429,
 0.9382,
 0.9356,
 0.9105,
 0.9509,
 0.9622,
 0.9526,
 0.946,
 0.9465,
 0.9653,
 0.9663,
 0.9598,
 0.9519,
 0.9613,
 0.9581,
 0.9691,
 0.9692]