<a href="https://colab.research.google.com/github/7201krap/PYTORCH_introduction_to_pytorch/blob/main/2_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import torch
import numpy as np

In [5]:
x = torch.empty(3)  # 1d vector with three elements 
print(x)

tensor([1.6349e-35, 0.0000e+00, 5.0447e-44])


In [7]:
y = torch.empty(2, 3)   # 2d vector with 2 X 3
print(y)

tensor([[1.6350e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [9]:
z = torch.empty(2, 3, 4)    # 3d vector with 2 X 3 X 4 
print(z)

tensor([[[1.6553e-35, 0.0000e+00, 7.0065e-44, 6.8664e-44],
         [6.3058e-44, 6.7262e-44, 7.0065e-44, 6.3058e-44],
         [6.7262e-44, 7.7071e-44, 1.1771e-43, 6.8664e-44]],

        [[7.1466e-44, 8.1275e-44, 7.0065e-44, 7.9874e-44],
         [8.1275e-44, 6.8664e-44, 7.9874e-44, 6.4460e-44],
         [7.4269e-44, 7.5670e-44, 7.1466e-44, 7.0065e-44]]])


In [15]:
rand_x = torch.rand(2, 2)
print(rand_x)

tensor([[0.9196, 0.3791],
        [0.7322, 0.6980]])


In [20]:
zeros_x = torch.zeros(2, 2, dtype=torch.int)
print(zeros_x)
print(zeros_x.dtype)

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)
torch.int32


In [22]:
ones_x = torch.ones(2, 2)
print(ones_x)
print(ones_x.dtype)
print(ones_x.size())

tensor([[1., 1.],
        [1., 1.]])
torch.float32
torch.Size([2, 2])


In [23]:
x_tensor_list = torch.tensor([1,2,3,0.1])
print(x_tensor_list)

tensor([1.0000, 2.0000, 3.0000, 0.1000])


In [31]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

z1 = x + y
z2 = torch.add(x, y)
print(z1 == z2)

print(z)    # element-wise addition

tensor([[0.6406, 0.5349],
        [0.2301, 0.7555]])
tensor([[0.6679, 0.7044],
        [0.6313, 0.2662]])
tensor([[True, True],
        [True, True]])
tensor([[0.9184, 0.3009],
        [0.8888, 0.5495]])


In [32]:
m1 = x - y
m2 = torch.sub(x, y)
print(m1 == m2)

tensor([[True, True],
        [True, True]])


In [33]:
mul1 = x * y    # element-wise mulitplication 
mul2 = torch.mul(x, y)
print(mul1 == mul2)

tensor([[True, True],
        [True, True]])


In [34]:
div1 = x / y    # element-wise division 
div2 = torch.div(x, y)
print(div1 == div2)

tensor([[True, True],
        [True, True]])


In [42]:
# slicing
x = torch.rand(5, 3)
print(x)
print(x[:, 0])  # same as numpy 
print(x[1, :])
print(x[1, 1])
print(x[1, 1].item())  # if we have only one value in tensor, we can use item(). 
                       # item() gets the actual value 

tensor([[0.6274, 0.6687, 0.4308],
        [0.7622, 0.3593, 0.4629],
        [0.5988, 0.2072, 0.6199],
        [0.0630, 0.3514, 0.3422],
        [0.4917, 0.5147, 0.9803]])
tensor([0.6274, 0.7622, 0.5988, 0.0630, 0.4917])
tensor([0.7622, 0.3593, 0.4629])
tensor(0.3593)
0.35927635431289673


In [50]:
# reshaping
x = torch.rand(4, 4)
print(x)

y = x.view(16)
print(y)    # 1d vector 

print("===== reshaping/resizing =====")
z1 = x.view(2, 8)   
z2 = x.view(-1, 8)  # pytorch automatically finds a value for us 
print(z1)
print(z1.size())
print(z1 == z2)

tensor([[0.0656, 0.4130, 0.2222, 0.7570],
        [0.7709, 0.3075, 0.9301, 0.3476],
        [0.4060, 0.9690, 0.5617, 0.1507],
        [0.6053, 0.4215, 0.7154, 0.9495]])
tensor([0.0656, 0.4130, 0.2222, 0.7570, 0.7709, 0.3075, 0.9301, 0.3476, 0.4060,
        0.9690, 0.5617, 0.1507, 0.6053, 0.4215, 0.7154, 0.9495])
===== reshaping/resizing =====
tensor([[0.0656, 0.4130, 0.2222, 0.7570, 0.7709, 0.3075, 0.9301, 0.3476],
        [0.4060, 0.9690, 0.5617, 0.1507, 0.6053, 0.4215, 0.7154, 0.9495]])
torch.Size([2, 8])
tensor([[True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True]])


In [58]:
# numpy can be only dealt with cpu 
# torch -> numpy / numpy -> torch
a = torch.ones(5)
print(a)

print("===== tensor -> numpy =====")
b = a.numpy()
print(b)
print(type(b))
# a and b points to the "same memory location"

print("===== numpy -> tensor =====")
c = np.ones(5)
print(c)

d = torch.from_numpy(c)
print(d)
print(type(d))
# c and d points to the "same memory location"

tensor([1., 1., 1., 1., 1.])
===== tensor -> numpy =====
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
===== numpy -> tensor =====
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>
