<a href="https://colab.research.google.com/github/7201krap/PYTORCH_introduction_to_pytorch/blob/main/3_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import torch

In [19]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-1.0398,  2.2097, -1.6050], requires_grad=True)


In [20]:
y = x + 2
print(y)

tensor([0.9602, 4.2097, 0.3950], grad_fn=<AddBackward0>)


In [24]:
# without mean 
z1 = y * y * 2
print(z1)

tensor([ 1.8441, 35.4437,  0.3120], grad_fn=<MulBackward0>)


In [25]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)

In [26]:
z1.backward(v)    # calculate gradient dz/dx
print(x.grad)

tensor([7.6819e-01, 3.3678e+01, 3.1597e-03])


In [33]:
# with mean 
z2 = y * y * 2
z2 = z2.mean()
print(z2)

tensor(12.5333, grad_fn=<MeanBackward0>)


In [34]:
z2.backward()
print(x.grad)

tensor([ 2.4326, 56.1298,  0.5314])


In [40]:
x = torch.randn(3, requires_grad=True)
print(x)
# 1
# x.requires_grad_(False)
# print(x)

tensor([1.9028, 0.1058, 0.9027], requires_grad=True)


In [41]:
# 2 
# y = x.detach()
# print(y)

In [42]:
# 3
# with torch.no_grad():
#     y = x + 2
#     print(y)

tensor([3.9028, 2.1058, 2.9027])


In [47]:
# This is important 
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()    # we need to "flush the gradients" in weights 
                            # otherwise it would be accumulated 

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
