<a href="https://colab.research.google.com/github/7201krap/Introduction_to_Pytorch/blob/main/backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import torch

In [59]:
x = torch.ones(2, 2, requires_grad=True)

In [72]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [60]:
y = x + 1

In [61]:
y

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [62]:
z = 2*y**2

In [63]:
z

tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)

In [64]:
res = z.mean()

In [65]:
res

tensor(8., grad_fn=<MeanBackward0>)

In [69]:
res.backward()

In [75]:
# d_res / d_x == x.grad

# res = (z_1 + z_2 + z_3 + z_4) / 4
# z_i = 2 * y_i ** 2
# z_i = 2 * (x_i + 1) ** 2

In [74]:
x.grad

tensor([[2., 2.],
        [2., 2.]])